[project]
name = "dlio_s3_rust"
version = "0.3.0"
description = "A library of Rust code to access S3 in python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["maturin>=0.12"]
build-backend = "maturin"

[tool.maturin]
module-name = "dlio_s3_rust"

